FROM okapies/buildenv:linux-x64-gcc-6.4-base
MAINTAINER Yuta Okamoto <okapies@gmail.com>

RUN yum -y install zlib-devel curl-devel && \
    rm -rf /var/lib/apt/lists/*

RUN cd /usr/local/src && \
    wget https://cmake.org/files/v3.12/cmake-3.12.2.tar.gz && \
    echo '0f97485799e51a7070cc11494f3e02349b0fc3a24cc12b082e737bf67a0581a4  cmake-3.12.2.tar.gz' > cmake-3.12.2.tar.gz.sha256 && \
    sha256sum -c cmake-3.12.2.tar.gz.sha256 && \
    tar -zxf cmake-3.12.2.tar.gz && \
    cd cmake-3.12.2 && \
    ./bootstrap --parallel=$(nproc) --system-curl && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /usr/local/src/cmake-3.12.2 && \
    rm /usr/local/src/cmake-3.12.2.tar.gz*
